Update patch set 1
Patch Set 1: Code-Review-1

See report on https://review.lineageos.org/c/LineageOS/android_system_bt/+/238632 - it breaks here for me (patch applied without complaints, just like the rest of the patch set):


system/bt/stack/./avdt/avdt_scb_act.c:424:13: error: expected expression
            uint8_t sdes_type;
            ^
            if (sdes_type == AVDT_RTCP_SDES_CNAME) {
                ^
system/bt/stack/./avdt/avdt_scb_act.c:468:22: error: no member named 'stream_config' in 'tAVDT_SCB'

Patch-set: 1
Reviewer: Gerrit User 18939 <18939@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Code-Review=-1