Update patch set 1
Patch Set 1:

@Ethan on singlecore or -j1 builds only clean builds you always run into the imgdiff error.

Untill now i worked around that issue by building imgdiff with make before starting a rom build on singlecore.

Cant test this commit atm because build for me is broken without jack.

Not sure which commit broke builds without jack again.

actually error is:

 library jar [/home/mardon/android/system/out/target/common/obj/JAVA_LIBRARIES/telephony-common_intermediates/classes.jar]
Warning: library class org.cyanogenmod.internal.statusbar.ExternalQuickSettingsRecord depends on program class cyanogenmod.app.StatusBarPanelCustomTile
Warning: library class org.cyanogenmod.internal.statusbar.ExternalQuickSettingsRecord depends on program class cyanogenmod.app.StatusBarPanelCustomTile
Warning: library class org.cyanogenmod.internal.statusbar.ExternalQuickSettingsRecord depends on program class cyanogenmod.app.CustomTile
Warning: there were 3 instances of library classes depending on program classes.
         You must avoid such dependencies, since the program classes will
         be processed, while the library classes will remain unchanged.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#dependency)
Error: Please correct the above warnings first.
build/core/java.mk:536: recipe for target '/home/mardon/android/system/out/target/common/obj/APPS/CyanogenSetupWizard_intermediates/proguard.classes.jar' failed
make: *** [/home/mardon/android/system/out/target/common/obj/APPS/CyanogenSetupWizard_intermediates/proguard.classes.jar] Error 1
make: Leaving directory '/home/mardon/android/system'

Patch-set: 1