Update patch set 3
Patch Set 3:

missing something?
Build its broken:

  File "./build/tools/releasetools/ota_from_target_files", line 1767, in <module>
    main(sys.argv[1:])
  File "./build/tools/releasetools/ota_from_target_files", line 1722, in main
    WriteFullOTAPackage(input_zip, output_zip)
  File "./build/tools/releasetools/ota_from_target_files", line 687, in WriteFullOTAPackage
    system_items.Get("system").SetPermissions(script)
  File "./build/tools/releasetools/ota_from_target_files", line 348, in SetPermissions
    self.CountChildMetadata()
  File "./build/tools/releasetools/ota_from_target_files", line 305, in CountChildMetadata
    for k, v in i.CountChildMetadata().items():
  File "./build/tools/releasetools/ota_from_target_files", line 339, in CountChildMetadata
    best_dmode[1], best_fmode[1], best_selabel[1], best_capabilities[1])
TypeError: unsupported operand type(s) for +: 'int' and 'tuple'
make: *** [/home/tugapower/cm13/out/target/product/bacon/cm_bacon-ota-83cadeebbc.zip] Error 1

Patch-set: 3
Reviewer: Daniel Monteiro <12240@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0