Revert "roomservice: Add support for netrc"
Traceback (most recent call last):
File "build/tools/roomservice.py", line 41, in
authtuple = netrc.netrc().authenticators("api.github.com")
File "/usr/lib64/python2.7/netrc.py", line 31, in init
with open(file) as fp:
IOError: [Errno 2] No such file or directory: '/home/d4rk/.netrc'

This reverts commit 5882505f3690dcad87c142c7c57cd684366885be.

Change-Id: Ic9336b133349f03dfa6154b23b1929dc4af482bf