Update patch set 3
Patch Set 3:

clan angler build breaks:

hardware/qcom/camera/QCamera2/HAL/QCameraMem.cpp:40:29: fatal error: QComOMXMetadata.h: No such file or directory
 #include <QComOMXMetadata.h>

Patch-set: 3
Reviewer: LorD ClockaN <1458@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0