Update patch set 2
Patch Set 2:

> Patch Set 2: Code-Review+1
> 
> Manually reviewed the commits and compared to official 2018-12 security bulletin
> -> all fixes are present. Good job!
> 
> Will test on klte and serranoltexx (including the system_update_engine fix).
> 
> I had trouble picking the system_update_engine part automatically:
> 
> **************************
> # repopick -t n-asb-2018-12
> Applying change number 235814...
> ..
> Applying change number 235983...
> ERROR: For 235983, could not determine the project path for project LineageOS/android_system_update_engine
> **************************
> 
> Manually removing the folder system/update_engine + fresh "repo sync" didn't help.
> Explicit github/cm-14.1 branch checkout also didn't work.
> I worked around this by manually fetching the commit from gerrit.

Great job! Can I add you as a reviewer in the future? Also come join #cve on Slack.

For update_engine, you need to add a roomservice xml in .repo/local_manifests/ temporarily or edit .repo/manifests/default.xml (apply change from LineageOS/android project to repo manifests), and do repo sync again.

Patch-set: 2
Reviewer: Gerrit User 17868 <17868@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>