Update patch set 1
Patch Set 1:

Repopick breaks on 211322:

Applying change number 211322...
--> Subject:       "libmediaplayerservice:Fix deadlock on gapless start failure"
--> Project path:  frameworks/av
--> Change number: 211322 (Patch Set 211322)
['git fetch github', u'refs/changes/22/211322/2']
From https://github.com/LineageOS/android_frameworks_av
 * branch            refs/changes/22/211322/2 -> FETCH_HEAD
error: could not apply 5ae13b7... libmediaplayerservice:Fix deadlock on gapless start failure
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Recorded preimage for 'media/libmediaplayerservice/MediaPlayerService.cpp'
ERROR: git command failed

Patch-set: 1
CC: Stijn Segers <18939@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>