Bump Security String to 2025-11-01
* This version dies here because several patches from 2025-12-01 are not
  patchable but are applicable.

```
https://review.lineageos.org/c/LineageOS/android_frameworks_opt_telephony/+/466078
class CommandParamsFactory does not get the context passed as parameter for its constructor in versions less than R. Having the context however is the prereq for the fix; the commit introducing this is a major change in R.
I know that there are ways to dynamically obtain the context, but the mentioned "major change" is really characetrised by passing the given context through all method calls in telephony.
Therefore I am not sure, that a simple [...]getContext() in the fixed codesnippet is the right way to proceed here...
=> The vuln. as such however applies, so we cannot say "does not apply to P"
```

```
The SQLite update was left out as well in P_asb_2025-12:
https://review.lineageos.org/c/LineageOS/android_external_sqlite/+/466071
Attempting to use sqlite 3.32.4 throws the below error:
error: external/sqlite/android/Android.bp:1:1: "libsqlite3_android" depends on undefined module "libandroidicu"
libandroidicu was instroduced in Q, and attempting to pick it into external/icu comes with a big tail of further dependency issues...
```

```
And finally, the dng_sdk update was left out:
https://review.lineageos.org/c/LineageOS/android_external_dng_sdk/+/466049
Cherry-picking is really easy, the needed small adaptations are no-brainers. BUT:
error: external/dng_sdk/Android.bp:123:1: module "libdng_sdk" variant "linux_glibc_x86_64_static": stl: "c++_shared" is not a supported STL
And this depends heavily on bionic
```


Change-Id: Ib673dbac77b37a2b415422f9792feb0dccda7470