Update patch set 4
Patch Set 4:

Can't apply the patchset with "repopick -b -t n-asb-2020-09", fails here:

########################################################
Applying change number 285834...
--> Subject:       "DO NOT MERGE - Only autoVerify at install for new hosts"
--> Project path:  frameworks/base
--> Change number: 285834 (Patch Set 3)
['git fetch github', u'refs/changes/34/285834/3']
From https://github.com/LineageOS/android_frameworks_base
 * branch                    refs/changes/34/285834/3 -> FETCH_HEAD
error: could not apply 3afe56629d4... DO NOT MERGE - Only autoVerify at install for new hosts
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Recorded preimage for 'services/core/java/com/android/server/pm/PackageManagerService.java'
Recorded preimage for 'services/core/java/com/android/server/pm/Settings.java'
ERROR: git command failed
########################################################

Hints on solving this?

Thanks in advance.

Patch-set: 4
CC: Gerrit User 22631 <22631@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>