check_boot_jars: Add CAF IMS to whitelist
Fixes:
Error: /srv/out/target/common/obj/JAVA_LIBRARIES/telephony-common_intermediates/classes.jar
  contains class file org/codeaurora/ims/ImsMultiIdentityControllerBase$MultiIdentityBinder.class,
  which is not in the whitelist

(The error only pops up when using "make dist")

Change-Id: Ie16fb539c53d59a9e8ca44a974e4c2259fdeaf05