Update patch set 1
Patch Set 1: Verified-1

On z3, appears to cause a failure:

Error: inflate failed [invalid stored block lengths] at file offset [6896757]
imgdiff only supports gzip kernel compression, did you try CONFIG_KERNEL_LZO?
failed to break apart source image
make: *** [/opt/jenkins/android/workspace/android/cm-12.1/out/target/product/z3/obj/PACKAGING/recovery_patch_intermediates/recovery_from_boot.p] Error 1
make: *** Waiting for unfinished jobs....

http://jenkins.cyanogenmod.org/job/android/123048/console

Patch-set: 1