Update patch set 2
Patch Set 2:

Currently I can't build due to fatal errors during repopick.
What I did: repo sync --force-sync, followed by repopick_topic n-asb-2021-06
Result: fatal error:
Applying change number 312463...
--> Subject:       "Bump Security String to 2021-06-05"
--> Project path:  build
--> Change number: 312463 (Patch Set 2)
['git fetch github', u'refs/changes/63/312463/2']
From https://github.com/LineageOS/android_build
 * branch                refs/changes/63/312463/2 -> FETCH_HEAD
error: Cherry-picking is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: cherry-pick failed
ERROR: git command failed

Patch-set: 2