Update patch set 2
Patch Set 2:

This breaks lunch for acclaim among others (flo, encore):
:~/BUILD/cm-13.0$ lunch cm_acclaim-userdebug
Looking for dependencies
Adding dependencies to manifest
Traceback (most recent call last):
  File "build/tools/roomservice.py", line 238, in <module>
    fetch_dependencies(repo_path)
  File "build/tools/roomservice.py", line 221, in fetch_dependencies
    add_to_manifest(fetch_list, fallback_branch)
  File "build/tools/roomservice.py", line 176, in add_to_manifest
    if exists_in_tree(lm, repo_target):
  File "build/tools/roomservice.py", line 92, in exists_in_tree
    if child.attrib['path'] == repository:
NameError: global name 'repository' is not defined

** Don't have a product spec for: 'cm_acclaim'
** Do you have the right repo manifest?

Patch-set: 2
Reviewer: David Marble <2644@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0